### ISSUE TITLE
求修改一下目录的翻译~~

### ISSUE THREAD

**Issue by zengyun-hacker** [trans4fun/The-Swift-Programming-Language#30]
建议“protocol”的翻译由“接口”改为“协议”
“type casting”翻译由"类型检查"改为“类型转换”

**Comment by siemenliu** [comment]
赞晓毒，确实之前翻译的有点不合适 已更正 https://github.com/trans4fun/The-Swift-Programming-Language/commit/0f981a79462247de62cd660f94401fc6df6e7921
